# Chapter 3 - Exercise 1a: 

### Các kiến thức sử dụng trong bài tập:

#### Tạo mảng (numpy array):
1. Tạo mảng có giá trị trong khoảng từ a đến b - 1: <p style="color:blue">biến_mảng = np.arange(a, b)</p>
2. Tạo mảng từ 1 dãy số cho trước: <p style="color:blue">biến_mảng = np.array([dãy số])</p>
3. Tạo mảng theo điều kiện từ mảng đã có: <p style="color:blue">biến_mảng_mới = biến_mảng[<điều kiện>]</p>ví dụ: <span style="color:blue">arr_even = arr[arr % 2 == 0]</span>

#### Các thao tác trên mảng:
Xem số phần tử có trong mảng: <span style="color:blue">biến_mảng.shape</span>


#### Thực hiện các yêu cầu sau và đối chiếu với kết quả cho trước:

In [5]:
import numpy as np

In [27]:
# Câu 1: Tạo numpy array có giá trị từ 0-9 và lưu vào biến arr
np_a = np.arange(0,10)
# Hiển thị các phần tử có trong arr
print(np_a)
# Xem kiểu dữ liệu (type) của arr
print(type(np_a))
# Xem kích thước (shape) của arr
print(np_a.)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
10


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
  <pre>[0 1 2 3 4 5 6 7 8 9]
&lt;class 'numpy.ndarray'&gt;
(10,)
</pre>

</details>

In [18]:
# Câu 2: Từ array arr ở câu 1 => tạo arr_odd và arr_even 
arr_odd = np_a[np_a%2 == 1]
arr_even = np_a[np_a%2 == 0]
# Hiển thị các phần tử có trong arr_odd và arr_even
print('Odd array:')
print(arr_odd)
print('Even array:')
print(arr_even)

Odd array:
[1 3 5 7 9]
Even array:
[0 2 4 6 8]


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
 <pre>Odd array:
[1 3 5 7 9]
Even array:
[0 2 4 6 8]
</pre>

</details>

In [59]:
# Câu 3: Từ array arr ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100
arr_update_1 = np_a[np_a%2 == 0]
arr_update_1 = np.insert(arr_update_1, np.arange(1,arr_update_1.shape[0] + 1), 100)
# Hiển thị các phần tử có trong arr_update_1
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]


<details>
  <summary>Nhấn vào đây để xem kết quả !</summary>
  
 <pre>[  0 100   2 100   4 100   6 100   8 100]
</pre>

</details>