In [1]:
import numpy as np
import random
from scipy.linalg import cholesky


In [2]:
##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)

            # Thêm giá trị vào dòng hiện hành 
            row.append(a)

        # Thêm dòng vào ma trận    
        mtr.append(row)

    return np.array(mtr)


In [3]:
## a) Tạo ma trận A(3 x 3) chứa các giá trị ngẫu nhiên trong khoảng 3 - 9
m, n, min, max = 3, 3, 3, 9
A = create_matrix_random(m, n, min, max)
print('Ma trận A', A.shape, ':\n', A)

Ma trận A (3, 3) :
 [[4 7 5]
 [9 7 4]
 [9 5 9]]


In [4]:
## b) Chuyển A thành ma trận vuông đối xứng theo tam giác dưới
for i in range(A.shape[0]):
    for j in range(i):
        A[j][i] = A[i][j]


In [5]:
## c) Thực hiện phân rã Cholesky, nếu có thể
## Kiểm tra ma trận xác định dương
test = np.linalg.eigvalsh(A)

pos_def = np.all(test > 0)
if (pos_def == True):
    L = cholesky(A)

    print('Ma trận L', L.shape, ':\n', L)

    print('Tái tạo ma trận A:\n', L.dot(L.T))
else:
    print('Không thỏa điều kiện xác định dương')

Không thỏa điều kiện xác định dương


In [7]:
##------------------------------------------------------------------------------
## Hàm tạo ma trận xác định dương    
##------------------------------------------------------------------------------
def create_matrix_positive_definite(m, n, start, end):
    A = None
    pos_def = False

    while (pos_def == False):
        A = create_matrix_random(m, n, start, end)
        for i in range(A.shape[0]):
            for j in range(i):
                A[j][i] = A[i][j]
        test = np.linalg.eigvalsh(A)
        pos_def = np.all(test > 0)
    return A


In [8]:
A = create_matrix_positive_definite(3, 3, 3, 9)
L = cholesky(A)
print('Ma trận L', L.shape, ':\n', L)

print('Tái tạo ma trận A:\n', L.dot(L.T))


Ma trận L (3, 3) :
 [[ 3.16227766  1.26491106  2.52982213]
 [ 0.          2.7202941  -0.07352146]
 [ 0.          0.          1.89594161]]
Tái tạo ma trận A:
 [[18.          3.25493388  4.79639504]
 [ 3.25493388  7.40540541 -0.1393924 ]
 [ 4.79639504 -0.1393924   3.59459459]]
