In [1]:
import numpy as np
from numpy.linalg import eig

In [2]:
## a) Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
m, n, min, max = 4, 4, 1, 9
A = np.random.randint(1, 10, (n, n))
print('Ma trận A', A.shape, ':\n', A)

Ma trận A (4, 4) :
 [[1 5 8 2]
 [3 7 9 6]
 [2 8 1 3]
 [7 7 6 9]]


In [3]:
## b) Tạo ma trận đối xứng B = A.A_T
B = A @ A.T
print('Ma trận đối xứng B', B.shape, ':\n', B)

Ma trận đối xứng B (4, 4) :
 [[ 94 122  56 108]
 [122 175  89 178]
 [ 56  89  78 103]
 [108 178 103 215]]


In [4]:
## c) Phân tích eigenvalues và eigenvectors
values, vectors = eig(B)

print('Eigenvalues',  values.shape,  ':\n', values)
print('Eigenvectors', vectors.shape, ':\n', vectors)

Eigenvalues (4,) :
 [4.99503936e+02 4.96226012e-01 3.93539994e+01 2.26458382e+01]
Eigenvectors (4, 4) :
 [[-0.38936149 -0.60754137 -0.6581309  -0.21483678]
 [-0.58343111  0.73450045 -0.34468506  0.03618602]
 [-0.32937585 -0.00270472  0.46551497 -0.82146214]
 [-0.63207382 -0.30231649  0.48099038  0.52700633]]
