In [1]:
import numpy as np
import random

from numpy.linalg import eig, inv
from numpy import diag

In [2]:
##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)

            # Thêm giá trị vào dòng hiện hành 
            row.append(a)

        # Thêm dòng vào ma trận    
        mtr.append(row)

    return np.array(mtr)

In [3]:
## a) Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
m, n, min, max = 5, 5, 1, 10
A = create_matrix_random(m, n, min, max)
print('Ma trận A', A.shape, ':\n', A)


Ma trận A (5, 5) :
 [[ 9  7  3  2  7]
 [ 1 10  8  2  6]
 [10  2 10 11  3]
 [10  3  4 10  4]
 [ 9  6  6  3  8]]


In [4]:
## b) Phân tích eigenvalues và eigenvectors
values, vectors = eig(A)

print('Eigenvalues', values.shape, ':\n', values)
print('Eigenvectors', vectors.shape, ':\n', vectors)


Eigenvalues (5,) :
 [30.65630588+0.j          6.17982313+6.16159266j  6.17982313-6.16159266j
  1.35774812+0.j          2.62629975+0.j        ]
Eigenvectors (5, 5) :
 [[ 0.39220921+0.j         -0.38182303+0.15990494j -0.38182303-0.15990494j
   0.25984625+0.j          0.00241848+0.j        ]
 [ 0.40041628+0.j         -0.15808988-0.54648146j -0.15808988+0.54648146j
   0.53917953+0.j         -0.69731069+0.j        ]
 [ 0.52967294+0.j          0.60180031+0.j          0.60180031-0.j
   0.00989463+0.j          0.18809451+0.j        ]
 [ 0.43973974+0.j          0.20661524+0.27251291j  0.20661524-0.27251291j
  -0.12629691+0.j         -0.18338086+0.j        ]
 [ 0.46034148+0.j         -0.14578041+0.0681066j  -0.14578041-0.0681066j
  -0.79102247+0.j          0.6668912 +0.j        ]]


In [5]:
## c) Kiểm tra eigenvector đầu tiên theo dot và theo eigenvalue có bằng nhau?
##    Nếu bằng nhau thì tái tạo A từ các eigenvalues và eigenvectors
B = A.dot(vectors[:, 0])
print('Ma trận B:\n', B)

C = vectors[:, 0] * values[0]
print('Ma trận C:\n', C)

Q = vectors
R = inv(Q)
L = diag(values)

print('Tái tạo ma trận A:\n', Q.dot(L).dot(R))


Ma trận B:
 [12.02368549+0.j 12.27528386+0.j 16.23781563+0.j 13.48079602+0.j
 14.11236925+0.j]
Ma trận C:
 [12.02368549+0.j 12.27528386+0.j 16.23781563+0.j 13.48079602+0.j
 14.11236925+0.j]
Tái tạo ma trận A:
 [[ 9.-9.64976226e-16j  7.-1.14051721e-16j  3.-5.95220455e-16j
   2.+1.97353173e-15j  7.-2.47244977e-16j]
 [ 1.-7.85624779e-16j 10.+2.19743393e-16j  8.-1.73334066e-16j
   2.-3.78404752e-16j  6.+7.51593782e-17j]
 [10.-4.91473469e-16j  2.+8.07896732e-17j 10.-1.00463923e-15j
  11.+1.49689422e-15j  3.+2.94286305e-16j]
 [10.-6.00761329e-16j  3.+1.12531737e-17j  4.-1.11048811e-15j
  10.+1.92176446e-15j  4.+2.04159072e-16j]
 [ 9.-7.86695481e-16j  6.-1.13565820e-16j  6.-6.06665857e-16j
   3.+1.80779400e-15j  8.-2.54411562e-16j]]
