In [1]:
import numpy as np
from scipy.linalg import pinv

In [2]:
## a) Tạo ma trận A(4 x 6) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
A = np.array([[4, 0], [3, -5]])
A = np.random.randint(1, 11, (4, 6))
print('Ma trận A', A.shape, ':\n', A)

Ma trận A (4, 6) :
 [[10 10  8  7  3  3]
 [ 3  4  8 10  1  1]
 [10  6  2  6  9  9]
 [ 5  6  3  3  6  7]]


In [4]:
## b) Tạo ma trận giả nghịch đảo của A
print('***** Cách 1: Dùng hàm scipy.linalg.pinv() *****')
B = pinv(A)
print('Ma trận giả nghịch đảo B', B.shape, 'của A:\n', B)
print('Kiểm chứng A @ B = I(m)', (A @ B).shape, ':\n', A @ B)
print('Kiểm chứng B @ A = I(n)', (B @ A).shape, ':\n', B @ A)


***** Cách 1: Dùng hàm scipy.linalg.pinv() *****
Ma trận giả nghịch đảo B (6, 4) của A:
 [[ 0.09138077 -0.06626429  0.1196076  -0.20033402]
 [ 0.07174093 -0.04746491 -0.10477189  0.12741926]
 [ 0.0118247   0.04230158 -0.09444617  0.10769099]
 [-0.0539694   0.10225392  0.08001261 -0.09470558]
 [-0.05115176  0.01146002  0.03606198  0.03977202]
 [-0.06485782  0.01624061 -0.02035398  0.13708088]]
Kiểm chứng A @ B = I(m) (4, 4) :
 [[ 1.00000000e+00  8.04911693e-16 -3.55271368e-15  5.93969318e-15]
 [ 5.13478149e-16  1.00000000e+00  2.94209102e-15 -4.35762537e-15]
 [ 5.27355937e-16  2.77555756e-16  1.00000000e+00 -2.10942375e-15]
 [ 1.94289029e-16  1.94289029e-16 -1.38777878e-17  1.00000000e+00]]
Kiểm chứng B @ A = I(n) (6, 6) :
 [[ 0.9094207   0.16439198 -0.16085506  0.09366599  0.0823423  -0.11799171]
 [ 0.16439198  0.66343391  0.3669222  -0.21883613 -0.01067357  0.11674569]
 [-0.16085506  0.3669222   0.56719086  0.26218464 -0.12609395 -0.01840296]
 [ 0.09366599 -0.21883613  0.26218464  0.8

In [5]:

print('\n***** Cách 2: Dùng công thức tính toán *****')
## Phân rã SVD
U, s, VT = np.linalg.svd(A)
print('         - Ma trận U',   U.shape, ':\n', U)
print('         - Eigenvalues:', s, '\n')
print('         - Ma trận V.T', VT.shape, ':\n', VT)

## Nghịch đảo của ma trận đường chéo S
S_1 = np.zeros(A.T.shape)
d   = 1.0 / s
S_1[:A.shape[0],:A.shape[0]] = np.diag(d)

print('         - Ma trận nghịch đảo của S', S_1.shape, ':\n', S_1)
B = (VT.T) @ S_1 @ U.T

print('Ma trận giả nghịch đảo TRÁI B', B.shape, 'của A:\n', B)
print('Kiểm chứng A @ B = I(m)', (A @ B).shape, ':\n', A @ B)
print('Kiểm chứng B @ A = I(n)', (B @ A).shape, ':\n', B @ A)


***** Cách 2: Dùng công thức tính toán *****
         - Ma trận U (4, 4) :
 [[-0.59166064 -0.33567546 -0.72618165 -0.09959862]
 [-0.37579678 -0.68867352  0.61856125  0.04344574]
 [-0.58457942  0.5497656   0.29341973 -0.51954744]
 [-0.40863353  0.33287918  0.06282557  0.847504  ]]
         - Eigenvalues: [29.4468075  11.13438573  5.0432448   2.73434903] 

         - Ma trận V.T (6, 6) :
 [[-0.50711639 -0.45434709 -0.34417038 -0.42900982 -0.33496992 -0.34884692]
 [ 0.1562077  -0.07324876 -0.54754912 -0.44360169  0.47146432  0.50136082]
 [-0.42786096 -0.52547512 -0.01698252  0.6050343   0.28904949  0.30150686]
 [-0.66692415  0.4189429   0.3855375  -0.30629066  0.05622798  0.36617524]
 [-0.26687012  0.39396965 -0.29657462  0.1604515   0.57079404 -0.57798031]
 [-0.13913893  0.42585679 -0.58724155  0.36543532 -0.50299058  0.26055944]]
         - Ma trận nghịch đảo của S (6, 4) :
 [[0.03395954 0.         0.         0.        ]
 [0.         0.08981187 0.         0.        ]
 [0.         0.   