In [1]:
import numpy as np
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [3]:
# a) Tạo ma trận có các giá trị "ngẫu nhiên"
print('\n*** a) Tạo ma trận có các giá trị ngẫu nhiên từ 1 đến 255:')
# set random seed to repeat
np.random.seed(190)
A = np.random.randint(1, 256, (3000,3))
print('         - Matrix A', A.shape, ': \n', A[0:10], '\n')


*** a) Tạo ma trận có các giá trị ngẫu nhiên từ 1 đến 255:
         - Matrix A (3000, 3) : 
 [[ 79 141  44]
 [ 38  89 111]
 [  4  88 105]
 [149  72 135]
 [101  94 138]
 [ 22  85 105]
 [100 237 186]
 [ 58 165 124]
 [197 177  37]
 [165 242  69]] 



In [4]:
print('\n*** b) Tính PCA:')
# column means\n",
M = mean(A.T, axis = 1)
print('         - Mean vectors M:', M, '\n')



*** b) Tính PCA:
         - Mean vectors M: [126.01266667 126.57733333 126.186     ] 



In [5]:
# center columns by subtracting column means
C = A - M
print('         - Center matrix C', C.shape, ': \n', C[0:10], '\n')


         - Center matrix C (3000, 3) : 
 [[ -47.01266667   14.42266667  -82.186     ]
 [ -88.01266667  -37.57733333  -15.186     ]
 [-122.01266667  -38.57733333  -21.186     ]
 [  22.98733333  -54.57733333    8.814     ]
 [ -25.01266667  -32.57733333   11.814     ]
 [-104.01266667  -41.57733333  -21.186     ]
 [ -26.01266667  110.42266667   59.814     ]
 [ -68.01266667   38.42266667   -2.186     ]
 [  70.98733333   50.42266667  -89.186     ]
 [  38.98733333  115.42266667  -57.186     ]] 



In [6]:
# calculate covariance matrix of centered matrix
V = cov(C.T)
print('         - Covariance matrix V', V.shape, ': \n', V, '\n')

         - Covariance matrix V (3, 3) : 
 [[5332.68140002   83.51886006  -59.08071624]
 [  83.51886006 5425.84196688  106.27337379]
 [ -59.08071624  106.27337379 5608.3741954 ]] 



In [7]:
# factorize covariance matrix
eigenvalues, eigenvectors = eig(V)

print('\n*** b) Eigendecomposition:')
print('         - Eigenvectors P', eigenvectors.shape, ': \n', eigenvectors, '\n')
print('         - Eigenvalues Lambda', eigenvalues.shape, ': \n', eigenvalues, '\n')



*** b) Eigendecomposition:
         - Eigenvectors P (3, 3) : 
 [[-0.78030613  0.62203136 -0.06480225]
 [ 0.55224511  0.7339544   0.39539383]
 [-0.29350927 -0.2727415   0.91622289]] 

         - Eigenvalues Lambda (3,) : 
 [5251.34970535 5457.13299907 5658.41485788] 



In [8]:
# project data
P = eigenvectors.T.dot(C.T)
print(P.T)

[[  68.77147141    3.75775968  -66.55153416]
 [  52.38215614  -78.18483555  -23.06818757]
 [  80.12137491  -98.43140729  -26.75764212]
 ...
 [  23.27167441  -91.31931987 -107.24695672]
 [-115.87133389    2.29863061  -63.9237229 ]
 [ -39.65243049  126.97690536   76.19053965]]
