In [1]:
import numpy as np
import random
from scipy.linalg import lu

In [2]:
##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)

            # Thêm giá trị vào dòng hiện hành 
            row.append(a)

        # Thêm dòng vào ma trận    
        mtr.append(row)

    return np.array(mtr)

In [3]:
## a) Tạo ma trận A(4 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
## Ma trận HÌNH CHỮ NHẬT: A(m, n) = P_T(m, m).L(m, n).U(n, n)
m, n, min, max = 5, 4, 1, 10
A = create_matrix_random(m, n, min, max)
print('Ma trận A', A.shape, ':\n', A)

Ma trận A (5, 4) :
 [[ 4  6  8  9]
 [ 8  8  5  9]
 [ 7  6  8  1]
 [10  1  7  8]
 [ 4  7  4  3]]


In [5]:
## b) Phân tích thành các thành phần P, L, U. In kết quả
P_T, L, U = lu(A)

print('Ma trận P_T', P_T.shape, ':\n', P_T)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)

Ma trận P_T (5, 5) :
 [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
Ma trận L (5, 4) :
 [[1.         0.         0.         0.        ]
 [0.8        1.         0.         0.        ]
 [0.4        0.77777778 1.         0.        ]
 [0.7        0.73611111 0.625      1.        ]
 [0.4        0.91666667 0.30882353 0.42253521]]
Ma trận U (4, 4) :
 [[10.          1.          7.          8.        ]
 [ 0.          7.2        -0.6         2.6       ]
 [ 0.          0.          5.66666667  3.77777778]
 [ 0.          0.          0.         -8.875     ]]


In [6]:
## c) Tái tạo lại ma trận B từ các thành phần P, L, U
print('Tái tạo ma trận A:\n', P_T.dot(L).dot(U))

Tái tạo ma trận A:
 [[ 4.  6.  8.  9.]
 [ 8.  8.  5.  9.]
 [ 7.  6.  8.  1.]
 [10.  1.  7.  8.]
 [ 4.  7.  4.  3.]]
