In [2]:
import numpy as np
import pandas as pd


In [3]:
LDS3folder = 'E:\Data Science\Mathematics and Statistics for Data Science\Excercise'
folder = LDS3folder + '/Data/B2/'

## a) Đọc tập tin iris vào dataframe
iris = pd.read_csv(folder + 'iris.csv')
print('\n*** a) Dataframe iris.csv:\n', iris.head())

X = iris[['sepal_length','sepal_width','petal_length','petal_width']]
print('\n       - 4 cột đầu tiên:\n', X.head())


*** a) Dataframe iris.csv:
    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

       - 4 cột đầu tiên:
    sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [4]:
## b) Phân tích SVD: U, s, VT
U, s, VT = np.linalg.svd(X)

print('\n*** b) Phân tích SVD:')
print('         - Ma trận U(', U.shape[1], ', ', U.shape[0], '): \n', U, '\n')
print('         - Eigenvalues:', s, '\n')
print('         - Ma trận VT(', VT.shape[1], ', ', VT.shape[0], '): \n', VT, '\n')



*** b) Phân tích SVD:
         - Ma trận U( 150 ,  150 ): 
 [[-6.16171172e-02  1.29969428e-01 -5.58364155e-05 ... -9.34637342e-02
  -9.60224157e-02 -8.09922905e-02]
 [-5.80722977e-02  1.11371452e-01  6.84386629e-02 ...  3.66755322e-02
  -3.24463474e-02  1.27273399e-02]
 [-5.67633852e-02  1.18294769e-01  2.31062793e-03 ...  3.08252776e-02
   1.95234663e-01  1.35567696e-01]
 ...
 [-9.40702260e-02 -4.98348018e-02 -4.14958083e-02 ...  9.81822841e-01
  -2.17978813e-02 -8.85972146e-03]
 [-9.48993908e-02 -5.62107520e-02 -2.12386574e-01 ... -2.14264126e-02
   9.42038920e-01 -2.96933496e-02]
 [-8.84882764e-02 -5.16210172e-02 -9.51442925e-02 ... -8.52768485e-03
  -3.02139863e-02  9.73577349e-01]] 

         - Eigenvalues: [95.95066751 17.72295328  3.46929666  1.87891236] 

         - Ma trận VT( 4 ,  4 ): 
 [[-0.75116805 -0.37978837 -0.51315094 -0.16787934]
 [ 0.28583096  0.54488976 -0.70889874 -0.34475845]
 [ 0.49942378 -0.67502499 -0.05471983 -0.54029889]
 [ 0.32345496 -0.32124324 -0.48077482

In [5]:
## c) Tạo dataframe mới từ U, s, VT
X1 = np.matrix(U[:, :2]) * np.diag(s[:2]) * np.matrix(VT[:2, :])

print('\n*** c) NEW dataframe (using only the first two components):')
print('         - X1.shape():', X1.shape)
Xnew = pd.DataFrame(X1, index = X.index, columns = X.columns)
print(Xnew.head())


*** c) NEW dataframe (using only the first two components):
         - X1.shape(): (150, 4)
   sepal_length  sepal_width  petal_length  petal_width
0      5.099453     3.500508      1.400946     0.198406
1      4.749747     3.191730      1.460070     0.254941
2      4.690479     3.210891      1.308639     0.191555
3      4.618348     3.084397      1.462666     0.267318
4      5.078961     3.500519      1.363524     0.183240


In [6]:
## d) Tìm error
print('\n*** d) Error from actual value:')
print((X - X1).head())


*** d) Error from actual value:
   sepal_length  sepal_width  petal_length  petal_width
0      0.000547    -0.000508     -0.000946     0.001594
1      0.150253    -0.191730     -0.060070    -0.054941
2      0.009521    -0.010891     -0.008639     0.008445
3     -0.018348     0.015603      0.037334    -0.067318
4     -0.078961     0.099481      0.036476     0.016760


In [7]:
## e) Tái tạo ma trận
Sigma = np.zeros_like(X)
Sigma[:X.shape[1], :X.shape[1]] = np.diag(s)
print(Sigma.shape)

X_c = U.dot(Sigma.dot(VT))
print(X_c[0:5])

X_c_new = pd.DataFrame(X_c, columns = X.columns)
print(X_c_new.head())

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
